# Database Configuration
source_db:
  type: postgresql  # or mysql
  host: 192.168.64.1  # Docker service name
  port: 5432
  user: admin
  password: root
  database: check_db_source

target_db:
  type: postgresql  # or mysql
  host: 192.168.64.1  # Docker service name
  port: 5432
  user: admin
  password: root
  database: check_db_target


# Validation Settings
validation:
  interval_minutes: 5
  types:
    - row_count
    - hash_check
    - sample_comparison
  sample_size: 1000
  chunk_size: 10000
  
  # Hash validation sampling settings (for performance on large tables)
  hash_sampling:
    enabled: true                    # Enable sampling for hash validation
    max_rows_for_full_scan: 100000   # Tables with more rows will use sampling
    sample_size: 10000               # Number of rows to sample for large tables
    sample_method: "random"          # "random" or "systematic"
  
  # Maximum number of detailed hash mismatches to log (prevents excessive logging)
  max_detailed_mismatches: 20
  
  # Fix query generation settings
  generate_fix_queries: true         # Enable generation of MySQL UPDATE queries for differences
  fix_queries_file: logs/fix-query.sql  # File to save generated fix queries
  max_fix_queries: null              # Maximum number of fix queries to generate (null = unlimited, set to number to limit)
  
  # Row count validation settings
  row_count_missing_detection:
    enabled: true                    # Enable detection of missing rows when count mismatch occurs
    max_missing_rows_to_log: 50     # Maximum number of missing rows to log in detail
    max_table_size_for_detection: 1000000  # Skip missing row detection for tables larger than this
  
  # Columns to ignore during hash validation (commonly added by ETL tools)
  ignored_columns:
    - _dlt_load_id
    - _dlt_id
    - _extracted_at
    - _loaded_at

# Table Settings
tables:
  include: []  # Empty list means all tables
  exclude: []
  name_mapping: {}  # Source to target table name mapping

# Server Settings
server:
  host: 0.0.0.0
  port: 8000
  health_check_path: /health

# Logging Settings
logging:
  level: INFO
  file: logs/data_checker.log
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}" 